# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0184274e3c897cf5689531d2cec5be8091e85b9e04f82e35c0ea76bd9d1eb2c5e012f1cb3d4a927e647c07ec3201e511a8129f7ef6a7fd93da9f1bd7be1a13b8

test:
  secret_key_base: c764a2cd3cebab75df82b41300f17431eae9fc574b1906fa9395bf7800fa30c694bec23cd82e043891bb84cde4cd6cf8b4fa5f3abc73227b7d0c15f34d5938c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
